export const CLEAN_STATE = 'CLEAN_STATE';

export const LIST_REQUEST = 'LIST_REQUEST';
export const LIST_SUCCESS_ACTIVE = 'LIST_SUCCESS_ACTIVE'
export const LIST_SUCCESS = 'LIST_SUCCESS';
export const LIST_FAIL = 'LIST_FAIL';

export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const CREATE_FAIL = 'CREATE_FAIL';

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';
export const UPDATE_FAIL = 'UPDATE_FAIL';


export const DELETE_SUCCESS = 'UPDATE_SUCCESS';
export const DELETE_FAIL = 'UPDATE_FAIL';

